# Who Becomes an Inventor? The Importance of Exposure to Innovation

- paper: https://academic.oup.com/qje/article/134/2/647/5218522#133115189

- download data 
https://dataverse.harvard.edu/file.xhtml?persistentId=doi:10.7910/DVN/UITDYS/TSMZ80&version=1.2

```sh
($) wget 'https://dataverse.harvard.edu/api/access/datafile/:persistentId?persistentId=doi:10.7910/DVN/UITDYS/TSMZ80'
```

In [8]:
import pandas as pd 
import numpy as np
import matplotlib.pylab as plt
import seaborn as sns

# Table 1: Origins of Inventors

> Innovation Rates by Childhood CZ/State, Gender and Parent Income

- table_1a: Innovation Rates by Childhood CZ

In [10]:
path = 'code_and_data/data/excel/table_1a.csv'
df = pd.read_csv(path)

print(df.shape)
# df.head(3)
df.describe().T

(741, 140)

,count,mean,std,min,25%,50%,75%,max
par_cz,741.0,22443.815115,11125.539098,100.0,12701.000000,26106.000000,31301.000000,39400.000000
kid_count,722.0,21677.360111,51516.309774,250.0,2743.250000,7013.500000,18856.000000,749352.000000
inventor,722.0,0.001697,0.001275,0.0,0.000778,0.001473,0.002424,0.009585
top5cit,722.0,0.000066,0.000128,0.0,0.000000,0.000000,0.000100,0.001252
inventor_cat_1,722.0,0.000146,0.000234,0.0,0.000000,0.000081,0.000220,0.003571
...,...,...,...,...,...,...,...,...
top5cit_cat_3_pq_5,523.0,0.000023,0.000178,0.0,0.000000,0.000000,0.000000,0.003401
top5cit_cat_4_pq_5,523.0,0.000021,0.000118,0.0,0.000000,0.000000,0.000000,0.001818
top5cit_cat_5_pq_5,523.0,0.000019,0.000170,0.0,0.000000,0.000000,0.000000,0.003597
top5cit_cat_6_pq_5,523.0,0.000021,0.000108,0.0,0.000000,0.000000,0.000000,0.001302
top5cit_cat_7_pq_5,523.0,0.000048,0.000153,0.0,0.000000,0.000000,0.000000,0.001658